server:
  port: 8206


spring:
  application:
    name: service-order

  profiles:
    active: dev

#mysql数据库
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1017
    url: jdbc:mysql://localhost:3306/yygh_order?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true

#返回json全局时间格式
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  data:
    mongodb:
      uri: mongodb://192.168.206.127:27017/yygh_hosp
      host: 172.17.0.1
      port: 27017
      database: yygh_hosp


  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848


#  rabbitMq
  rabbitmq:
    host: 192.168.206.117
    port: 5672
    username: root
    password: 1017


#配置mapper xml文件路径
#mybatis-plus:
#  mapper-locations: classpath:com/alex/yygh/serviceorder/mapper/xml/*.xml

