server:
  port: 80


spring:
  application:
    name: server-gateway

  #nacos
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

    gateway:
      discovery:
        locator:
          enabled: true



      routes:
        - id: service-hosp
          uri: lb://service-hosp
          predicates:
            - Path=/*/hosp/**

        - id: service-cmn
          uri:  lb://service-cmn
          predicates:
            - Path=/*/cmn/**

        - id: service-user
          uri: lb://service-user
          predicates:
            - Path=/*/user/**,/*/ucenter/**


        - id: service-msm
          uri: lb://service-msm
          predicates:
            - Path=/*/msm/**


        - id: service-oss
          uri: lb://service-oss
          predicates:
            - Path=/*/oss/**

        - id: service-order
          uri: lb://service-order
          predicates:
            - Path=/*/order/**

        - id: service-statistics
          uri:  lb://service-statistics
          predicates:
            - Path=/*/statistics/**
