server:
  port: 8160

spring:
  application:
    name: service-user

#环境设置: dev、test、prod
  profiles:
    active: dev

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1017
    url: jdbc:mysql://localhost:3306/yygh_user?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true


  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  cloud:
    nacos:
      discovery:
        server-addr: 192.168.2.17:8848

  redis:
    host: 192.168.206.129
    database: 0
    timeout: 1800000
    lettuce:
      pool:
        max-active: 20
        max-wait: -1
        max-idle: 5
        min-idle: 0

mybatis-plus:
  mapper-locations: classpath:com/alex/yygh/serviceuser/mapper/xml/*.xml


wx:
  open:
    app_id: wxed9954c01bb89b47
    app_secret: a7482517235173ddb4083788de60b90e
#    这个是微信后台配置的地址，后台有个域名服务，老师把他重定向到 localhost:8160
    redirect_url: http://localhost:8160/api/ucenter/wx/callback
yygh:
  baseUrl:  http://localhost:3000
